# Generated by Django 4.2 on 2023-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarefa', models.CharField(max_length=20)),
                ('disciplina', models.CharField(max_length=20)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
