# Generated by Django 4.2 on 2023-05-02 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tarefa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_disciplina', to='tarefas.disciplina'),
        ),
    ]
